-- ========================
-- DROP (옵션)
-- ========================
BEGIN
    FOR t IN (SELECT table_name FROM user_tables) LOOP
        EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS';
    END LOOP;
END;
/

-- ========================
-- 1. 기본 테이블 (참조 대상 먼저)
-- ========================

CREATE TABLE USERS (
    USER_NO NUMBER PRIMARY KEY,
    USER_NAME VARCHAR2(50) NOT NULL,
    EMAIL VARCHAR2(100),
    PHONE VARCHAR2(50),
    PROVIDER VARCHAR2(50),
    CREATED_AT DATE NOT NULL,
    STATUS VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
    DELETE_AT DATE,
    AUTH NUMBER NOT NULL
);

CREATE TABLE STOCKS (
    STOCK_CODE VARCHAR2(8) PRIMARY KEY,
    STOCK_NAME VARCHAR2(100) NOT NULL,
    MARKET_TYPE VARCHAR2(20),
    SECTOR VARCHAR2(50),
    LISTED_DATE DATE,
    STATUS VARCHAR2(20) DEFAULT 'ACTIVE'
);

-- ========================
-- 2. 종속 테이블
-- ========================

CREATE TABLE ACCOUNTS (
    ACCOUNT_NO NUMBER PRIMARY KEY,
    USER_NO NUMBER NOT NULL,
    INITIAL_BALANCE NUMBER,
    CREATED_AT DATE,
    STATUS VARCHAR2(15) DEFAULT 'ACTIVE' NOT NULL
);

CREATE TABLE ACCOUNT_BALANCE (
    ACCOUNT_NO NUMBER PRIMARY KEY,
    AVAILABLE_CASH NUMBER,
    LOCKED_CASH NUMBER
);

CREATE TABLE STOCKS_HELD (
    STOCKS_HELD_NO NUMBER PRIMARY KEY,
    ACCOUNT_NO NUMBER NOT NULL,
    STOCK_CODE VARCHAR2(8) NOT NULL,
    STOCK_RESERVES NUMBER,
    AVG_PRICE NUMBER,
    CONSTRAINT UQ_ACC_STOCK UNIQUE (ACCOUNT_NO, STOCK_CODE)
);

CREATE TABLE BOARD (
    BOARD_NO NUMBER PRIMARY KEY,
    USER_NO NUMBER NOT NULL,
    CONTENT VARCHAR2(2000) NOT NULL,
    CREATED_AT DATE NOT NULL,
    LIKE_COUNT NUMBER,
    PARENT_ID NUMBER,
    STOCK_CODE VARCHAR2(8) NOT NULL
);

CREATE TABLE BOARD_LIKE (
    BOARD_NO NUMBER,
    USER_NO NUMBER
);

CREATE TABLE ORDERS (
    ORDER_ID NUMBER PRIMARY KEY,
    ORDER_KIND VARCHAR2(5) NOT NULL,
    ORDER_TYPE VARCHAR2(7) NOT NULL,
    PRICE NUMBER NOT NULL,
    QUANTITY NUMBER NOT NULL,
    STATUS VARCHAR2(10) DEFAULT 'PENDING' NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    USER_NO NUMBER NOT NULL,
    STOCK_CODE VARCHAR2(8) NOT NULL,
    CHECK (ORDER_KIND IN ('BUY','SELL')),
    CHECK (ORDER_TYPE IN ('MARKET','LIMIT'))
);

CREATE TABLE TRADES (
    TRADE_ID NUMBER PRIMARY KEY,
    ORDER_ID NUMBER NOT NULL,
    PRICE NUMBER NOT NULL,
    QUANTITY NUMBER NOT NULL,
    EXECUTED_AT TIMESTAMP NOT NULL
);

CREATE TABLE WATCHLIST (
    USER_NO NUMBER,
    STOCK_CODE VARCHAR2(8),
    PRIMARY KEY (USER_NO, STOCK_CODE)
);

CREATE TABLE NEWS (
    NEWS_ID NUMBER PRIMARY KEY,
    NEWS_TITLE VARCHAR2(500) NOT NULL,
    PUBLISHER VARCHAR2(100) NOT NULL,
    PUBLISHED_AT DATE NOT NULL
);

CREATE TABLE NEWS_STOCK (
    NEWS_ID NUMBER,
    STOCK_CODE VARCHAR2(8),
    PRIMARY KEY (NEWS_ID, STOCK_CODE)
);

CREATE TABLE USER_LOCAL (
    USER_NO NUMBER,
    USER_ID VARCHAR2(50) UNIQUE,
    PASSWORD VARCHAR2(100)
);

CREATE TABLE USER_SOCIAL (
    SOCIAL_NO NUMBER PRIMARY KEY,
    PROVIDER_ID VARCHAR2(100) NOT NULL,
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
    USER_NO NUMBER
);

CREATE TABLE STOCK_PRICE_TICK (
    TICK_ID NUMBER PRIMARY KEY,
    STOCK_CODE VARCHAR2(8),
    PRICE NUMBER,
    VOLUME NUMBER,
    TIMESTAMP TIMESTAMP
);

CREATE TABLE STOCK_ANALYSIS (
    ANALYSIS_ID NUMBER PRIMARY KEY,
    STOCK_CODE VARCHAR2(8),
    SIGNAL VARCHAR2(5),
    CONFIDENCE NUMBER,
    CREATED_AT DATE
);

CREATE TABLE RECENT_VIEW (
    USER_NO NUMBER,
    STOCK_CODE VARCHAR2(8),
    VIEWED_AT TIMESTAMP
);

CREATE TABLE co_information (
    CORP_CODE VARCHAR2(10) PRIMARY KEY,
    STOCK_CODE VARCHAR2(8),
    CO_NAME VARCHAR2(100),

    ISSUED_STOCK NUMBER,
    DECLINED_STOCK NUMBER,
    TREASURY_STOCK NUMBER,
    OUTSTANDING_SHARES NUMBER,

    MINORITY_SHAREHOLDER_RATIO NUMBER(5,2),
    MINORITY_OWNERSHIP_RATIO NUMBER(5,2),

    UPDATED_AT DATE
);

CREATE TABLE NOTICE (
    NOTICE_ID NUMBER PRIMARY KEY,
    TITLE VARCHAR2(255),
    CONTENT VARCHAR2(2000),
    CREATED_AT DATE,
    UPDATED_AT DATE,
    USER_NO NUMBER
);

CREATE TABLE INVESTMENT_TYPE (
	USER_NO	NUMBER		NOT NULL,
	TOTAL_POINT	NUMBER		NULL,
	RESULT_FILE	VARCHAR2(500)		NULL
);

CREATE TABLE stock_realtime (
	STOCK_REALTIME_ID	NUMBER		NOT NULL,
	STOCK_CODE	VARCHAR2(8)		NOT NULL,
	CURRENT_PRICE	NUMBER		NULL,
	OPEN_PRICE	NUMBER		NULL,
	CHANGE_PRICE	NUMBER		NULL,
	CHANGE_RATE	NUMBER		NULL,
	VOLUME	NUMBER		NULL,
	UPDATED_AT	TIMESTAMP		NULL
);

-- ========================
-- 3. FK (마지막에 몰아서)
-- ========================

ALTER TABLE ACCOUNTS ADD CONSTRAINT FK_ACC_USER
FOREIGN KEY (USER_NO) REFERENCES USERS(USER_NO);

ALTER TABLE ACCOUNT_BALANCE ADD CONSTRAINT FK_BAL_ACC
FOREIGN KEY (ACCOUNT_NO) REFERENCES ACCOUNTS(ACCOUNT_NO);

ALTER TABLE STOCKS_HELD ADD CONSTRAINT FK_SH_ACC
FOREIGN KEY (ACCOUNT_NO) REFERENCES ACCOUNTS(ACCOUNT_NO);

ALTER TABLE STOCKS_HELD ADD CONSTRAINT FK_SH_STOCK
FOREIGN KEY (STOCK_CODE) REFERENCES STOCKS(STOCK_CODE);

ALTER TABLE BOARD ADD CONSTRAINT FK_BOARD_USER
FOREIGN KEY (USER_NO) REFERENCES USERS(USER_NO);

ALTER TABLE BOARD ADD CONSTRAINT FK_BOARD_STOCK
FOREIGN KEY (STOCK_CODE) REFERENCES STOCKS(STOCK_CODE);

ALTER TABLE BOARD ADD CONSTRAINT FK_BOARD_PARENT
FOREIGN KEY (PARENT_ID) REFERENCES BOARD(BOARD_NO);

ALTER TABLE BOARD_LIKE ADD CONSTRAINT FK_BL_BOARD
FOREIGN KEY (BOARD_NO) REFERENCES BOARD(BOARD_NO);

ALTER TABLE BOARD_LIKE ADD CONSTRAINT FK_BL_USER
FOREIGN KEY (USER_NO) REFERENCES USERS(USER_NO);

ALTER TABLE ORDERS ADD CONSTRAINT FK_ORDER_USER
FOREIGN KEY (USER_NO) REFERENCES USERS(USER_NO);

ALTER TABLE ORDERS ADD CONSTRAINT FK_ORDER_STOCK
FOREIGN KEY (STOCK_CODE) REFERENCES STOCKS(STOCK_CODE);

ALTER TABLE TRADES ADD CONSTRAINT FK_TRADE_ORDER
FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID);

ALTER TABLE WATCHLIST ADD CONSTRAINT FK_WATCH_USER
FOREIGN KEY (USER_NO) REFERENCES USERS(USER_NO);

ALTER TABLE WATCHLIST ADD CONSTRAINT FK_WATCH_STOCK
FOREIGN KEY (STOCK_CODE) REFERENCES STOCKS(STOCK_CODE);

ALTER TABLE NEWS_STOCK ADD CONSTRAINT FK_NS_NEWS
FOREIGN KEY (NEWS_ID) REFERENCES NEWS(NEWS_ID);

ALTER TABLE NEWS_STOCK ADD CONSTRAINT FK_NS_STOCK
FOREIGN KEY (STOCK_CODE) REFERENCES STOCKS(STOCK_CODE);

ALTER TABLE USER_LOCAL ADD CONSTRAINT FK_UL_USER
FOREIGN KEY (USER_NO) REFERENCES USERS(USER_NO);

ALTER TABLE USER_SOCIAL ADD CONSTRAINT FK_US_USER
FOREIGN KEY (USER_NO) REFERENCES USERS(USER_NO);

ALTER TABLE STOCK_PRICE_TICK ADD CONSTRAINT FK_TICK_STOCK
FOREIGN KEY (STOCK_CODE) REFERENCES STOCKS(STOCK_CODE);

ALTER TABLE STOCK_ANALYSIS ADD CONSTRAINT FK_ANALYSIS_STOCK
FOREIGN KEY (STOCK_CODE) REFERENCES STOCKS(STOCK_CODE);

ALTER TABLE RECENT_VIEW ADD CONSTRAINT FK_RV_USER
FOREIGN KEY (USER_NO) REFERENCES USERS(USER_NO);

ALTER TABLE RECENT_VIEW ADD CONSTRAINT FK_RV_STOCK
FOREIGN KEY (STOCK_CODE) REFERENCES STOCKS(STOCK_CODE);

ALTER TABLE CO_INFORMATION ADD CONSTRAINT FK_CO_STOCK
FOREIGN KEY (STOCK_CODE) REFERENCES STOCKS(STOCK_CODE);

ALTER TABLE NOTICE ADD CONSTRAINT FK_NOTICE_USER
FOREIGN KEY (USER_NO) REFERENCES USERS(USER_NO);

-- ========================
-- 4. SEQUENCE(PK값 자동생성)
-- ========================

CREATE SEQUENCE SEQ_STOCKS_HELD START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_NEWS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_NOTICE START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_ACCOUNTS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_STOCK_REALTIME START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_BOARD START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_TRADES START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_CO_INFORMATION START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_USERS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_STOCK_ANALYSIS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_USER_SOCIAL START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_STOCK_PRICE_TICK START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_ORDERS START WITH 1 INCREMENT BY 1;

-- ========================
-- 5. COMMENT(주석)
-- ========================

COMMENT ON COLUMN STOCKS_HELD.STOCKS_HELD_NO IS '보유주식고유코드';
COMMENT ON COLUMN STOCKS_HELD.ACCOUNT_NO IS '계좌 고유 번호';
COMMENT ON COLUMN STOCKS_HELD.STOCK_CODE IS '종목코드(6자리)';
COMMENT ON COLUMN STOCKS_HELD.STOCK_RESERVES IS '보유량(보유주수)';
COMMENT ON COLUMN STOCKS_HELD.AVG_PRICE IS '구매당시 평균값';

COMMENT ON COLUMN ACCOUNT_BALANCE.ACCOUNT_NO IS '계좌 고유 번호(PK로 만들면 좋음)';
COMMENT ON COLUMN ACCOUNT_BALANCE.AVAILABLE_CASH IS '가용가능한 금액(잔액)';
COMMENT ON COLUMN ACCOUNT_BALANCE.LOCKED_CASH IS '주문에 묶인 돈';

COMMENT ON COLUMN NEWS.NEWS_ID IS '뉴스 고유 번호';
COMMENT ON COLUMN NEWS.NEWS_TITLE IS '뉴스 제목';
COMMENT ON COLUMN NEWS.PUBLISHER IS '언론사';
COMMENT ON COLUMN NEWS.PUBLISHED_AT IS '발행시간';

COMMENT ON COLUMN notice.notice_id IS '고유번호';
COMMENT ON COLUMN notice.title IS '제목';
COMMENT ON COLUMN notice.content IS '내용';
COMMENT ON COLUMN notice.created_at IS '생성시간';
COMMENT ON COLUMN notice.updated_at IS '업데이트 시간';
COMMENT ON COLUMN notice.USER_NO IS '유저 고유 번호';

COMMENT ON COLUMN ACCOUNTS.ACCOUNT_NO IS '계좌 고유 번호';
COMMENT ON COLUMN ACCOUNTS.USER_NO IS '유저 고유 번호';
COMMENT ON COLUMN ACCOUNTS.INITIAL_BALANCE IS '전일 금액(정각 마다 초기화)';
COMMENT ON COLUMN ACCOUNTS.CREATED_AT IS '계좌 생성일';
COMMENT ON COLUMN ACCOUNTS.STATUS IS '정상, 파산, 정지';

COMMENT ON COLUMN stock_realtime.STOCK_REALTIME_ID IS '실시간 시세 고유코드';
COMMENT ON COLUMN stock_realtime.STOCK_CODE IS '종목코드(6자리)';
COMMENT ON COLUMN stock_realtime.CURRENT_PRICE IS '현재가';
COMMENT ON COLUMN stock_realtime.OPEN_PRICE IS '장 시작가';
COMMENT ON COLUMN stock_realtime.CHANGE_PRICE IS '변경가';
COMMENT ON COLUMN stock_realtime.CHANGE_RATE IS '변동률';
COMMENT ON COLUMN stock_realtime.VOLUME IS '거래량';
COMMENT ON COLUMN stock_realtime.UPDATED_AT IS '분단위(하루만)';

COMMENT ON COLUMN USER_LOCAL.USER_NO IS '유저 고유 번호';
COMMENT ON COLUMN USER_LOCAL.USER_ID IS '유저 ID';
COMMENT ON COLUMN USER_LOCAL.PASSWORD IS '유저 비밀번호';

COMMENT ON COLUMN STOCKS.STOCK_CODE IS '종목코드(6자리)';
COMMENT ON COLUMN STOCKS.STOCK_NAME IS '종목명(회사명)';
COMMENT ON COLUMN STOCKS.MARKET_TYPE IS '시장';
COMMENT ON COLUMN STOCKS.SECTOR IS '업종';
COMMENT ON COLUMN STOCKS.LISTED_DATE IS '상장일';
COMMENT ON COLUMN STOCKS.STATUS IS '거래 상태(ACTIVE, DELISTED,SUSPENDED)';

COMMENT ON COLUMN INVESTMENT_TYPE.USER_NO IS '유저 고유 번호';
COMMENT ON COLUMN INVESTMENT_TYPE.TOTAL_POINT IS '설문 결과 총점';
COMMENT ON COLUMN INVESTMENT_TYPE.RESULT_FILE IS 'HTTP://~~(파일저장위치)';

COMMENT ON COLUMN BOARD.BOARD_NO IS '보드번호';
COMMENT ON COLUMN BOARD.USER_NO IS '유저 고유 번호';
COMMENT ON COLUMN BOARD.CONTENT IS '내용';
COMMENT ON COLUMN BOARD.CREATED_AT IS '생성 시간';
COMMENT ON COLUMN BOARD.LIKE_COUNT IS '좋아요 수';
COMMENT ON COLUMN BOARD.PARENT_ID IS '대댓글일시 부모되는 board_no';
COMMENT ON COLUMN BOARD.STOCK_CODE IS '종목코드(6자리)';

COMMENT ON COLUMN NEWS_STOCK.NEWS_ID IS '뉴스 고유 번호';
COMMENT ON COLUMN NEWS_STOCK.STOCK_CODE IS '종목코드(6자리)';

COMMENT ON COLUMN watchlist.USER_NO IS '유저 고유 번호';
COMMENT ON COLUMN watchlist.STOCK_CODE IS '종목코드(6자리)';

COMMENT ON COLUMN trades.trade_id IS '체결 고유 코드';
COMMENT ON COLUMN trades.order_id IS '주문 고유코드';
COMMENT ON COLUMN trades.price IS '체결된 금액';
COMMENT ON COLUMN trades.quantity IS '체결 수량';
COMMENT ON COLUMN trades.executed_at IS '체결 시간';

COMMENT ON COLUMN CO_INFORMATION.CORP_CODE IS '고유코드(8자리)';
COMMENT ON COLUMN CO_INFORMATION.STOCK_CODE IS '종목코드(6자리)';
COMMENT ON COLUMN CO_INFORMATION.CO_NAME IS '회사명';
COMMENT ON COLUMN CO_INFORMATION.ISSUED_STOCK IS '발행한 총 주식';
COMMENT ON COLUMN CO_INFORMATION.DECLINED_STOCK IS '감소한 총 주식';
COMMENT ON COLUMN CO_INFORMATION.TREASURY_STOCK IS '자기주식수';
COMMENT ON COLUMN CO_INFORMATION.OUTSTANDING_SHARES IS '유통주식수';
COMMENT ON COLUMN CO_INFORMATION.MINORITY_SHAREHOLDER_RATIO IS '주주 비율';
COMMENT ON COLUMN CO_INFORMATION.MINORITY_OWNERSHIP_RATIO IS '보유 주식 비율';
COMMENT ON COLUMN CO_INFORMATION.UPDATED_AT IS '최종 수정 시간';

COMMENT ON COLUMN BOARD_LIKE.BOARD_NO IS '보드 번호';
COMMENT ON COLUMN BOARD_LIKE.USER_NO IS '유저 고유 번호';

COMMENT ON COLUMN RECENT_VIEW.USER_NO IS '유저 고유 번호';
COMMENT ON COLUMN RECENT_VIEW.STOCK_CODE IS '종목코드(6자리)';
COMMENT ON COLUMN RECENT_VIEW.viewed_at IS '시간';

COMMENT ON COLUMN USERS.USER_NO IS '유저 고유 번호';
COMMENT ON COLUMN USERS.USER_NAME IS '이름';
COMMENT ON COLUMN USERS.EMAIL IS '이메일';
COMMENT ON COLUMN USERS.PHONE IS '전화번호';
COMMENT ON COLUMN USERS.PROVIDER IS '로컬, 소셜(카카오, 네이버)';
COMMENT ON COLUMN USERS.CREATED_AT IS '계정생성일';
COMMENT ON COLUMN USERS.STATUS IS '삭제 여부';
COMMENT ON COLUMN USERS.DELETE_AT IS '삭제 한날';
COMMENT ON COLUMN USERS.AUTH IS '관리자=1, 유저=2';

COMMENT ON COLUMN stock_analysis.STOCK_CODE IS '종목코드(6자리)';
COMMENT ON COLUMN stock_analysis.signal IS 'BUY/SELL';
COMMENT ON COLUMN stock_analysis.confidence IS '신뢰도';

COMMENT ON COLUMN USER_SOCIAL.SOCIAL_NO IS '고유번호';
COMMENT ON COLUMN USER_SOCIAL.PROVIDER_ID IS '소셜이 준 고유값';
COMMENT ON COLUMN USER_SOCIAL.CREATED_AT IS '이 소셜 계정이 우리 서비스에 연결된 시간';
COMMENT ON COLUMN USER_SOCIAL.USER_NO IS '유저 고유 번호';

COMMENT ON COLUMN stock_price_tick.tick_id IS '고유 번호';
COMMENT ON COLUMN stock_price_tick.STOCK_CODE IS '종목코드(6자리)';
COMMENT ON COLUMN stock_price_tick.PRICE IS '거래금액';
COMMENT ON COLUMN stock_price_tick.VOLUME IS '거래량';
COMMENT ON COLUMN stock_price_tick.TIMESTAMP IS '거래시간';

COMMENT ON COLUMN orders.order_id IS '주문 고유코드';
COMMENT ON COLUMN orders.order_kind IS '매도/매수(BUY/SELL)';
COMMENT ON COLUMN orders.order_type IS '시장가/지정가(MARKET/LIMIT)';
COMMENT ON COLUMN orders.price IS '주문 가격';
COMMENT ON COLUMN orders.quantity IS '주문 수량';
COMMENT ON COLUMN orders.status IS 'PENDING → 주문접수
PARTIAL → 일부 체결
FILLED → 전량 체결 완료
CANCELED → 취소
REJECTED -> 주문 거부';
COMMENT ON COLUMN orders.created_at IS '주문 시각';
COMMENT ON COLUMN orders.USER_NO IS '유저 고유 번호';
COMMENT ON COLUMN orders.STOCK_CODE IS '종목코드(6자리)';

-- ========================
-- 6. 주식데이터 저장 테이블 보수
-- ========================

DROP TABLE STOCK_REALTIME CASCADE CONSTRAINTS;
DROP TABLE STOCK_PRICE_TICK CASCADE CONSTRAINTS;

CREATE TABLE STOCK_REALTIME_CURRENT (
    STOCK_CODE         VARCHAR2(8)    NOT NULL,
    CURRENT_PRICE      NUMBER         NULL,
    OPEN_PRICE         NUMBER         NULL,
    CHANGE_PRICE       NUMBER         NULL,
    CHANGE_RATE        NUMBER         NULL,
    VOLUME             NUMBER         NULL,
    UPDATED_AT         TIMESTAMP      NULL,

    CONSTRAINT PK_STOCK_REALTIME_CURRENT
        PRIMARY KEY (STOCK_CODE)
);

CREATE TABLE STOCK_REALTIME_TICK (
    TICK_ID            NUMBER         NOT NULL,
    STOCK_CODE         VARCHAR2(8)    NOT NULL,
    CURRENT_PRICE      NUMBER         NULL,
    CHANGE_RATE        NUMBER         NULL,
    VOLUME             NUMBER         NULL,
    TRADE_TIME         TIMESTAMP      NULL,

    CONSTRAINT PK_STOCK_REALTIME_TICK
        PRIMARY KEY (TICK_ID)
);

CREATE TABLE STOCK_HISTORY_CACHE (
    HISTORY_ID         NUMBER         NOT NULL,
    STOCK_CODE         VARCHAR2(8)    NOT NULL,

    PERIOD_TYPE        VARCHAR2(1)    NOT NULL,
    BASE_DATE          DATE           NOT NULL,

    OPEN_PRICE         NUMBER         NULL,
    HIGH_PRICE         NUMBER         NULL,
    LOW_PRICE          NUMBER         NULL,
    CLOSE_PRICE        NUMBER         NULL,

    VOLUME             NUMBER         NULL,
    CHANGE_PRICE       NUMBER         NULL,
    CHANGE_RATE        NUMBER         NULL,

    CREATED_AT         TIMESTAMP      DEFAULT SYSTIMESTAMP,

    CONSTRAINT PK_STOCK_HISTORY_CACHE
        PRIMARY KEY (HISTORY_ID),

    CONSTRAINT CHK_STOCK_HISTORY_PERIOD
        CHECK (PERIOD_TYPE IN ('D', 'W', 'M'))
);

ALTER TABLE STOCK_REALTIME_CURRENT
ADD CONSTRAINT FK_SRC_STOCK
FOREIGN KEY (STOCK_CODE)
REFERENCES STOCKS(STOCK_CODE);

ALTER TABLE STOCK_REALTIME_TICK
ADD CONSTRAINT FK_SRT_STOCK
FOREIGN KEY (STOCK_CODE)
REFERENCES STOCKS(STOCK_CODE);

ALTER TABLE STOCK_HISTORY_CACHE
ADD CONSTRAINT FK_SHC_STOCK
FOREIGN KEY (STOCK_CODE)
REFERENCES STOCKS(STOCK_CODE);

CREATE SEQUENCE SEQ_STOCK_REALTIME_TICK START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_STOCK_HISTORY_CACHE START WITH 1 INCREMENT BY 1;

COMMENT ON COLUMN STOCK_REALTIME_CURRENT.STOCK_CODE IS '종목코드(6자리)';
COMMENT ON COLUMN STOCK_REALTIME_CURRENT.CURRENT_PRICE IS '현재가';
COMMENT ON COLUMN STOCK_REALTIME_CURRENT.OPEN_PRICE IS '장 시작가';
COMMENT ON COLUMN STOCK_REALTIME_CURRENT.CHANGE_PRICE IS '전일 대비 가격';
COMMENT ON COLUMN STOCK_REALTIME_CURRENT.CHANGE_RATE IS '등락률';
COMMENT ON COLUMN STOCK_REALTIME_CURRENT.VOLUME IS '거래량';
COMMENT ON COLUMN STOCK_REALTIME_CURRENT.UPDATED_AT IS '최근 체결 시간';

COMMENT ON COLUMN STOCK_REALTIME_TICK.TICK_ID IS 'Tick 고유번호';
COMMENT ON COLUMN STOCK_REALTIME_TICK.STOCK_CODE IS '종목코드(6자리)';
COMMENT ON COLUMN STOCK_REALTIME_TICK.CURRENT_PRICE IS '체결 현재가';
COMMENT ON COLUMN STOCK_REALTIME_TICK.CHANGE_RATE IS '등락률';
COMMENT ON COLUMN STOCK_REALTIME_TICK.VOLUME IS '체결 거래량';
COMMENT ON COLUMN STOCK_REALTIME_TICK.TRADE_TIME IS '체결 시간';

COMMENT ON COLUMN STOCK_HISTORY_CACHE.HISTORY_ID IS '과거시세 고유번호';
COMMENT ON COLUMN STOCK_HISTORY_CACHE.STOCK_CODE IS '종목코드(6자리)';
COMMENT ON COLUMN STOCK_HISTORY_CACHE.PERIOD_TYPE IS 'D=일봉 W=주봉 M=월봉';
COMMENT ON COLUMN STOCK_HISTORY_CACHE.BASE_DATE IS '기준 일자';
COMMENT ON COLUMN STOCK_HISTORY_CACHE.OPEN_PRICE IS '시가';
COMMENT ON COLUMN STOCK_HISTORY_CACHE.HIGH_PRICE IS '고가';
COMMENT ON COLUMN STOCK_HISTORY_CACHE.LOW_PRICE IS '저가';
COMMENT ON COLUMN STOCK_HISTORY_CACHE.CLOSE_PRICE IS '종가';
COMMENT ON COLUMN STOCK_HISTORY_CACHE.VOLUME IS '거래량';
COMMENT ON COLUMN STOCK_HISTORY_CACHE.CHANGE_PRICE IS '전일 대비';
COMMENT ON COLUMN STOCK_HISTORY_CACHE.CHANGE_RATE IS '등락률';
COMMENT ON COLUMN STOCK_HISTORY_CACHE.CREATED_AT IS '캐시 저장 시간';
