-- =====================================================
-- SEQUENCE
-- =====================================================

CREATE SEQUENCE SEQ_USER_NO START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE SEQ_ITEM_NO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_ITEM_IMG_NO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_ITEM_CD_NO START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE SEQ_BID_NO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_RESULT_NO START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE SEQ_BOARD_NO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_BOARD_IMG_NO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_BOARD_CD_NO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_REPLY_NO START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE SEQ_REPORT_NO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_REPORT_CD_NO START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE SEQ_NOTI_NO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_NOTI_CD_NO START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE SEQ_PAY_NO START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE SEQ_AUTH_NO START WITH 1 INCREMENT BY 1;

-- =====================================================
-- 권한
-- =====================================================

CREATE TABLE AUTHORITIES (

AUTHORITY NUMBER PRIMARY KEY,
AUTHORITY_NAME VARCHAR2(20) NOT NULL

);

COMMENT ON COLUMN AUTHORITIES.AUTHORITY IS '권한 번호 (PK)';
COMMENT ON COLUMN AUTHORITIES.AUTHORITY_NAME IS '권한 이름 (일반회원, 인증회원, 관리자)';

-- =====================================================
-- 회원
-- =====================================================

CREATE TABLE MEMBER (

USER_NO NUMBER PRIMARY KEY,

AUTHORITY NUMBER NOT NULL,

USER_ID VARCHAR2(20) NOT NULL UNIQUE,
USER_PWD VARCHAR2(100) NOT NULL,
USER_NAME VARCHAR2(20) NOT NULL,

USER_ADDRESS VARCHAR2(100),
USER_PHONE VARCHAR2(15),
USER_EMAIL VARCHAR2(50),

USER_ENROLL_DATE DATE DEFAULT SYSDATE,
USER_DELETE_YN CHAR(1) DEFAULT 'N',

USER_LOGIN_IP VARCHAR2(15),

PROFILE_IMG VARCHAR2(250) DEFAULT 'default.png',
INTRO VARCHAR2(200),

RATING_SCORE NUMBER(3,2) DEFAULT 0,
REVIEW_COUNT NUMBER DEFAULT 0,

CONSTRAINT FK_MEMBER_AUTH
FOREIGN KEY (AUTHORITY)
REFERENCES AUTHORITIES(AUTHORITY)

);

COMMENT ON COLUMN MEMBER.USER_NO IS '회원 고유번호 (PK)';
COMMENT ON COLUMN MEMBER.AUTHORITY IS '회원 권한 번호 (FK)';
COMMENT ON COLUMN MEMBER.USER_ID IS '회원 로그인 아이디';
COMMENT ON COLUMN MEMBER.USER_PWD IS '회원 암호화 비밀번호';
COMMENT ON COLUMN MEMBER.USER_NAME IS '회원 이름';
COMMENT ON COLUMN MEMBER.USER_ADDRESS IS '회원 주소';
COMMENT ON COLUMN MEMBER.USER_PHONE IS '회원 전화번호';
COMMENT ON COLUMN MEMBER.USER_EMAIL IS '회원 이메일';
COMMENT ON COLUMN MEMBER.USER_ENROLL_DATE IS '회원 가입일';
COMMENT ON COLUMN MEMBER.USER_DELETE_YN IS '회원 탈퇴 여부';
COMMENT ON COLUMN MEMBER.USER_LOGIN_IP IS '최근 로그인 IP';
COMMENT ON COLUMN MEMBER.PROFILE_IMG IS '프로필 이미지 경로';
COMMENT ON COLUMN MEMBER.INTRO IS '회원 자기소개';
COMMENT ON COLUMN MEMBER.RATING_SCORE IS '회원 평점';
COMMENT ON COLUMN MEMBER.REVIEW_COUNT IS '회원 리뷰 수';

-- =====================================================
-- 상품 카테고리
-- =====================================================

CREATE TABLE ITEM_CD (

ITEM_CD_NO NUMBER PRIMARY KEY,
ITEM_CD_NAME VARCHAR2(20) NOT NULL

);

COMMENT ON COLUMN ITEM_CD.ITEM_CD_NO IS '상품 카테고리 번호';
COMMENT ON COLUMN ITEM_CD.ITEM_CD_NAME IS '상품 카테고리 이름';

-- =====================================================
-- 상품
-- =====================================================

CREATE TABLE ITEM (

ITEM_NO NUMBER PRIMARY KEY,

ITEM_CD_NO NUMBER NOT NULL,
SELLER_NO NUMBER NOT NULL,

ITEM_TITLE VARCHAR2(50) NOT NULL,
ITEM_CONTENT VARCHAR2(200),

CREATE_COUNTRY VARCHAR2(20),

START_PRICE NUMBER DEFAULT 0,
CURRENT_PRICE NUMBER,

DIRECT_BUY CHAR(1) DEFAULT 'N',
BUY_NOW_PRICE NUMBER,

START_TIME DATE DEFAULT SYSDATE,
END_TIME DATE DEFAULT SYSDATE + 5,

STATUS VARCHAR2(20),

CREATE_AT DATE DEFAULT SYSDATE,

CONSTRAINT FK_ITEM_CATEGORY
FOREIGN KEY (ITEM_CD_NO)
REFERENCES ITEM_CD(ITEM_CD_NO),

CONSTRAINT FK_ITEM_SELLER
FOREIGN KEY (SELLER_NO)
REFERENCES MEMBER(USER_NO)

);

COMMENT ON COLUMN ITEM.ITEM_NO IS '상품 번호';
COMMENT ON COLUMN ITEM.ITEM_CD_NO IS '상품 카테고리 번호';
COMMENT ON COLUMN ITEM.SELLER_NO IS '판매자 회원번호';
COMMENT ON COLUMN ITEM.ITEM_TITLE IS '상품 제목';
COMMENT ON COLUMN ITEM.ITEM_CONTENT IS '상품 설명';
COMMENT ON COLUMN ITEM.CREATE_COUNTRY IS '제조 국가';
COMMENT ON COLUMN ITEM.START_PRICE IS '경매 시작 가격';
COMMENT ON COLUMN ITEM.CURRENT_PRICE IS '현재 입찰 가격';
COMMENT ON COLUMN ITEM.DIRECT_BUY IS '즉시 구매 가능 여부';
COMMENT ON COLUMN ITEM.BUY_NOW_PRICE IS '즉시 구매 가격';
COMMENT ON COLUMN ITEM.START_TIME IS '경매 시작 시간';
COMMENT ON COLUMN ITEM.END_TIME IS '경매 종료 시간';
COMMENT ON COLUMN ITEM.STATUS IS '상품 상태';
COMMENT ON COLUMN ITEM.CREATE_AT IS '상품 등록일';

-- =====================================================
-- 상품 이미지
-- =====================================================

CREATE TABLE ITEM_IMG (

ITEM_IMG_NO NUMBER PRIMARY KEY,

ITEM_NO NUMBER NOT NULL,

IMG_URL VARCHAR2(300) NOT NULL,

CONSTRAINT FK_ITEM_IMG
FOREIGN KEY (ITEM_NO)
REFERENCES ITEM(ITEM_NO)

);

COMMENT ON COLUMN ITEM_IMG.ITEM_IMG_NO IS '상품 이미지 번호';
COMMENT ON COLUMN ITEM_IMG.ITEM_NO IS '상품 번호';
COMMENT ON COLUMN ITEM_IMG.IMG_URL IS '상품 이미지 경로';

-- =====================================================
-- 입찰
-- =====================================================

CREATE TABLE BID (

BID_NO NUMBER PRIMARY KEY,

ITEM_NO NUMBER NOT NULL,
USER_NO NUMBER NOT NULL,

BID_PRICE NUMBER NOT NULL,

BID_TIME DATE DEFAULT SYSDATE,

CONSTRAINT FK_BID_ITEM
FOREIGN KEY (ITEM_NO)
REFERENCES ITEM(ITEM_NO),

CONSTRAINT FK_BID_USER
FOREIGN KEY (USER_NO)
REFERENCES MEMBER(USER_NO)

);

COMMENT ON COLUMN BID.BID_NO IS '입찰 번호';
COMMENT ON COLUMN BID.ITEM_NO IS '입찰 상품 번호';
COMMENT ON COLUMN BID.USER_NO IS '입찰 회원 번호';
COMMENT ON COLUMN BID.BID_PRICE IS '입찰 금액';
COMMENT ON COLUMN BID.BID_TIME IS '입찰 시간';

-- =====================================================
-- 낙찰
-- =====================================================

CREATE TABLE RESULT (

RESULT_NO NUMBER PRIMARY KEY,

ITEM_NO NUMBER NOT NULL,
BID_NO NUMBER NOT NULL,

FINAL_PRICE NUMBER,

RESULT_TIME DATE DEFAULT SYSDATE,

CONSTRAINT FK_RESULT_ITEM
FOREIGN KEY (ITEM_NO)
REFERENCES ITEM(ITEM_NO),

CONSTRAINT FK_RESULT_BID
FOREIGN KEY (BID_NO)
REFERENCES BID(BID_NO)

);

COMMENT ON COLUMN RESULT.RESULT_NO IS '낙찰 번호';
COMMENT ON COLUMN RESULT.ITEM_NO IS '낙찰 상품 번호';
COMMENT ON COLUMN RESULT.BID_NO IS '낙찰 입찰 번호';
COMMENT ON COLUMN RESULT.FINAL_PRICE IS '최종 낙찰 가격';
COMMENT ON COLUMN RESULT.RESULT_TIME IS '낙찰 처리 시간';

-- =====================================================
-- 결제
-- =====================================================

CREATE TABLE PAYMENT (

PAYMENT_NO NUMBER PRIMARY KEY,

RESULT_NO NUMBER NOT NULL,
BUYER_NO NUMBER NOT NULL,

AMOUNT NUMBER NOT NULL,

PAYMENT_METHOD VARCHAR2(20),

PAYMENT_STATUS VARCHAR2(1) DEFAULT 'N',

PAYMENT_TIME DATE DEFAULT SYSDATE,

CONSTRAINT FK_PAYMENT_RESULT
FOREIGN KEY (RESULT_NO)
REFERENCES RESULT(RESULT_NO),

CONSTRAINT FK_PAYMENT_USER
FOREIGN KEY (BUYER_NO)
REFERENCES MEMBER(USER_NO)

);

COMMENT ON COLUMN PAYMENT.PAYMENT_NO IS '결제 번호';
COMMENT ON COLUMN PAYMENT.RESULT_NO IS '낙찰 번호';
COMMENT ON COLUMN PAYMENT.BUYER_NO IS '구매자 회원번호';
COMMENT ON COLUMN PAYMENT.AMOUNT IS '결제 금액';
COMMENT ON COLUMN PAYMENT.PAYMENT_METHOD IS '결제 수단';
COMMENT ON COLUMN PAYMENT.PAYMENT_STATUS IS '결제 상태';
COMMENT ON COLUMN PAYMENT.PAYMENT_TIME IS '결제 시간';

-- =====================================================
-- 찜목록
-- =====================================================

CREATE TABLE WATCHLIST (

USER_NO NUMBER NOT NULL,
ITEM_NO NUMBER NOT NULL,

CONSTRAINT PK_WATCHLIST PRIMARY KEY (USER_NO, ITEM_NO),

CONSTRAINT FK_WATCH_USER
FOREIGN KEY (USER_NO)
REFERENCES MEMBER(USER_NO),

CONSTRAINT FK_WATCH_ITEM
FOREIGN KEY (ITEM_NO)
REFERENCES ITEM(ITEM_NO)

);

COMMENT ON COLUMN WATCHLIST.USER_NO IS '회원 번호';
COMMENT ON COLUMN WATCHLIST.ITEM_NO IS '찜 상품 번호';

-- =====================================================
-- 게시판 카테고리
-- =====================================================

CREATE TABLE BOARD_CATEGORY (

BOARD_CD_NO NUMBER PRIMARY KEY,
BOARD_CD VARCHAR2(20) NOT NULL

);

COMMENT ON COLUMN BOARD_CATEGORY.BOARD_CD_NO IS '게시판 카테고리 번호';
COMMENT ON COLUMN BOARD_CATEGORY.BOARD_CD IS '게시판 카테고리 이름';

-- =====================================================
-- 게시글
-- =====================================================

CREATE TABLE BOARD (

BOARD_NO NUMBER PRIMARY KEY,

BOARD_CD_NO NUMBER NOT NULL,
USER_NO NUMBER NOT NULL,

BOARD_TITLE VARCHAR2(100) NOT NULL,
BOARD_CONTENT VARCHAR2(4000),

BOARD_DATE DATE DEFAULT SYSDATE,

BOARD_COUNT NUMBER DEFAULT 0,
BOARD_COMMENT_COUNT NUMBER DEFAULT 0,

CONSTRAINT FK_BOARD_CATEGORY
FOREIGN KEY (BOARD_CD_NO)
REFERENCES BOARD_CATEGORY(BOARD_CD_NO),

CONSTRAINT FK_BOARD_USER
FOREIGN KEY (USER_NO)
REFERENCES MEMBER(USER_NO)

);

COMMENT ON COLUMN BOARD.BOARD_NO IS '게시글 번호';
COMMENT ON COLUMN BOARD.BOARD_CD_NO IS '게시판 카테고리 번호';
COMMENT ON COLUMN BOARD.USER_NO IS '작성자 회원번호';
COMMENT ON COLUMN BOARD.BOARD_TITLE IS '게시글 제목';
COMMENT ON COLUMN BOARD.BOARD_CONTENT IS '게시글 내용';
COMMENT ON COLUMN BOARD.BOARD_DATE IS '게시글 작성일';
COMMENT ON COLUMN BOARD.BOARD_COUNT IS '조회수';
COMMENT ON COLUMN BOARD.BOARD_COMMENT_COUNT IS '댓글 수';

-- =====================================================
-- 댓글
-- =====================================================

CREATE TABLE REPLY (

REPLY_NO NUMBER PRIMARY KEY,

BOARD_NO NUMBER NOT NULL,
USER_NO NUMBER NOT NULL,

REPLY_CONTENT VARCHAR2(400),

REPLY_DATE DATE DEFAULT SYSDATE,

CONSTRAINT FK_REPLY_BOARD
FOREIGN KEY (BOARD_NO)
REFERENCES BOARD(BOARD_NO),

CONSTRAINT FK_REPLY_USER
FOREIGN KEY (USER_NO)
REFERENCES MEMBER(USER_NO)

);

COMMENT ON COLUMN REPLY.REPLY_NO IS '댓글 번호';
COMMENT ON COLUMN REPLY.BOARD_NO IS '게시글 번호';
COMMENT ON COLUMN REPLY.USER_NO IS '댓글 작성자 번호';
COMMENT ON COLUMN REPLY.REPLY_CONTENT IS '댓글 내용';
COMMENT ON COLUMN REPLY.REPLY_DATE IS '댓글 작성일';

COMMIT;