CREATE TABLE "REPORT_CATEGORY" (
	"REPORT_CATEGORY_NO"	NUMBER	DEFAULT SEQ_REPORT_CATEGORY_NO	NOT NULL,
	"REPORT_CATEGORY"	VARCHAR2(30)		NOT NULL
);

COMMENT ON COLUMN "REPORT_CATEGORY"."REPORT_CATEGORY" IS '물품자랑
구매요망';

CREATE TABLE "NOTI_CD" (
	"NOTI_CATEGORY_NO"	NUMBER	DEFAULT SEQ_ITEM_CD_NO	NOT NULL,
	"NOTI_CATEGORY"	VARCHAR2(30)		NOT NULL
);

COMMENT ON COLUMN "NOTI_CD"."NOTI_CATEGORY" IS '예술
도서/문
근현대 생활사
등등';

CREATE TABLE "DELIVERY_DETAIL" (
	"DELIVERY_DETAIL_NO"	NUMBER	DEFAULT SEQ_DELIVERY_DETAIL_NO	NOT NULL,
	"DELIVERY_NO"	NUMBER		NOT NULL,
	"STATUS"	VARCHAR2		NULL,
	"SHIPPED_DATE"	DATE		NULL,
	"DELIVERED_DATE"	DATE		NULL
);

CREATE TABLE "BOARD_POST" (
	"BOARD_NO"	NUMBER	DEFAULT SEQ_BOARD_NO	NOT NULL,
	"BOARD_CD_NO"	NUMBER		NOT NULL,
	"USER_NO"	NUMBER		NOT NULL,
	"BOARD_TITLE"	VARCHAR2(100)		NOT NULL,
	"BOARD_CONTENT"	VARCHAR2(4000)		NOT NULL,
	"BOARD_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"VIEW_COUNT"	NUMBER	DEFAULT 0	NULL,
	"BOARD_DELETE"	VARCHAR2(1)	DEFAULT N	NOT NULL
);

CREATE TABLE "AUTHORITIES" (
	"AUTHORITY"	NUMBER	DEFAULT SEQ_AUTH_NO	NOT NULL,
	"AUTHORITI_NAME"	VARCHAR2(20)	DEFAULT USER	NOT NULL
);

COMMENT ON COLUMN "AUTHORITIES"."AUTHORITY" IS '1. 회원가입만 한 유저
2. 물품등록 본인인증 한 유저
3. 관리자';

COMMENT ON COLUMN "AUTHORITIES"."AUTHORITI_NAME" IS '1. USER
2. SUPER
3. ADMIN';

CREATE TABLE "DELIVERY" (
	"DELIVERY_NO"	NUMBER	DEFAULT SEQ_DELIVERY_NO	NOT NULL,
	"PAYMENT_NO"	NUMBER		NOT NULL,
	"BUYER_ID"	NUMBER		NOT NULL,
	"SELLER_ID"	NUMBER		NOT NULL,
	"RECEIVER_NAME"	VARCHAR2(20)		NOT NULL,
	"RECEIVER_PHONE"	NUMBER		NOT NULL,
	"POST_CODE"	NUMBER		NOT NULL,
	"ADDRESS"	VARCHAR2		NOT NULL,
	"ADDRESS_DETAIL"	VARCHAR2		NOT NULL,
	"DELIVERY_REQUEST"	VARCHAR2		NULL,
	"COURIER"	VARCHAR2		NULL,
	"TRACKING_NO"	NUMBER		NULL
);

CREATE TABLE "ITEM_IMG" (
	"ITEM_IMG_NO"	NUMBER	DEFAULT SEQ_ITEM_IMG_NO	NOT NULL,
	"ITEM_NO"	NUMBER		NOT NULL,
	"IMG_URL"	VARCHAR2(100)	DEFAULT HTTP://	NOT NULL
);

CREATE TABLE "USER_SANCTION" (
	"SANCTION_NO"	NUMBER	DEFAULT SEQ_SANCTION_NO	NOT NULL,
	"USER_NO"	NUMBER		NOT NULL,
	"SANCTIONED_AT"	DATE	DEFAULT SYSDATE	NOT NULL
);

CREATE TABLE "WISHLIST" (
	"USER_NO"	NUMBER		NOT NULL,
	"ITEM_NO"	NUMBER		NOT NULL
);

CREATE TABLE "RESULT" (
	"RESULT_NO"	NUMBER	DEFAULT SEQ_RESULT_NO	NOT NULL,
	"BID_NO"	NUMBER		NOT NULL,
	"FINAL_PRICE"	NUMBER		NULL,
	"RESULT_TIME"	DATE	DEFAULT SYSDATE	NOT NULL,
	"STATUS"	VARCHAR2(1)	DEFAULT Y	NOT NULL
);

CREATE TABLE "ITEM_CD" (
	"ITEM_CATEGORY_NO"	NUMBER	DEFAULT SEQ_ITEM_CATEGORY_NO	NOT NULL,
	"ITEM_CATEGORY"	VARCHAR2(30)		NOT NULL
);

COMMENT ON COLUMN "ITEM_CD"."ITEM_CATEGORY" IS '예술
도서/문
근현대 생활사
등등';

CREATE TABLE "BID" (
	"BID_NO"	NUMBER	DEFAULT SEQ_BID_NO	NOT NULL,
	"ITEM_NO"	NUMBER		NOT NULL,
	"USER_NO"	NUMBER		NOT NULL,
	"BID_PRICE"	NUMBER		NULL,
	"BID_TIME"	DATE	DEFAULT SYSDATE	NOT NULL,
	"Field"	NUMBER		NULL
);

COMMENT ON COLUMN "BID"."Field" IS '오로지 1,2위만';

CREATE TABLE "ITEM" (
	"ITEM_NO"	NUMBER	DEFAULT SEQ_ITEM_NO	NOT NULL,
	"ITEM_CD_NO"	NUMBER		NOT NULL,
	"USER_NO"	NUMBER		NOT NULL,
	"ITEM_TITLE"	VARCHAR2(50)		NOT NULL,
	"ITEM_SIZE"	NUMBER	DEFAULT 10	NOT NULL,
	"ITEM_CONTENT"	VARCHAR2(200)		NOT NULL,
	"START_PRICE"	NUMBER	DEFAULT 0	NOT NULL,
	"DIRECT_BUY"	VARCHAR2(1)	DEFAULT N	NOT NULL,
	"BUY_NOW_PRICE"	NUMBER	DEFAULT NULL	NULL,
	"CURRENT_PRICE"	NUMBER	DEFAULT NULL	NULL,
	"START_TIME"	DATE	DEFAULT SYSDATE	NOT NULL,
	"END_TIME"	DATE	DEFAULT SYSDATE+5	NOT NULL,
	"STATUS"	VARCHAR2(1)	DEFAULT Y	NOT NULL,
	"CREATE_AT"	DATE	DEFAULT SYSDATE	NOT NULL,
	"COUNTRY_NO"	VARCHAR2(3)		NOT NULL,
	"DELIVERY_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "ITEM"."DIRECT_BUY" IS 'CHECK ONLY ('Y' OR 'N')';

COMMENT ON COLUMN "ITEM"."BUY_NOW_PRICE" IS 'CHECK DIRECT_BUY 로 Y면 NOTNULL, DEFAULT는 99999999999';

COMMENT ON COLUMN "ITEM"."STATUS" IS 'Y : YET
N : NOW
E : END';

CREATE TABLE "REPLY" (
	"REPLY_NO"	NUMBER	DEFAULT SEQ_REPLY_NO	NOT NULL,
	"BOARD_NO"	NUMBER		NOT NULL,
	"USER_NO"	NUMBER		NOT NULL,
	"REPLY_CONTENT"	VARCHAR2(400)		NOT NULL,
	"REPLY_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"REPLY_DELETE"	VARCHAR2(1)	DEFAULT N	NOT NULL
);

CREATE TABLE "NOTIFICATION" (
	"NOTIFICATION_NO"	NUMBER	DEFAULT SEQ_NOTI_NO	NOT NULL,
	"NOTI_CD_NO"	NUMBER		NOT NULL,
	"USER_NO"	NUMBER		NOT NULL,
	"MESSAGE"	VARCHAR2(200)	DEFAULT NULL	NULL,
	"IS_READ"	VARCHAR2(1)	DEFAULT N	NOT NULL,
	"CREATE_AT"	DATE	DEFAULT SYSDATE	NOT NULL
);

CREATE TABLE "REPORT" (
	"REPORT_NO"	NUMBER	DEFAULT SEQ_REPORT_NO	NOT NULL,
	"USER_NO"	NUMBER		NOT NULL,
	"REPORT_CD_NO"	NUMBER		NOT NULL,
	"TARGET_TYPE"	VARCHAR2(10)		NOT NULL,
	"TARGET_NO"	NUMBER		NOT NULL,
	"STATUS"	VARCHAR2(1)	DEFAULT N	NOT NULL,
	"CREATED_AT"	DATE	DEFAULT SYSDATE	NOT NULL
);

CREATE TABLE "MEMBER" (
	"USER_NO"	NUMBER	DEFAULT SEQ_USER_NO	NOT NULL,
	"ATHORITY"	NUMBER		NOT NULL,
	"USER_ID"	VARCHAR2(20)		NOT NULL,
	"USER_PWD"	VARCHAR2(100)		NOT NULL,
	"USER_NAME"	VARCHAR2(20)		NOT NULL,
	"USER_ADDRESS"	VARCHAR2(100)		NULL,
	"USER_PHONE"	VARCHAR( 15)		NULL,
	"USER_EMAIL"	VARCHAR2(30)		NULL,
	"USER_ENROLL_DATE"	SYSDATE	DEFAULT SYSDATE	NOT NULL,
	"USER_DELETE_YN"	VARCHAR2(1)	DEFAULT N	NOT NULL,
	"USER_LOGIN_IP"	VARCHAR(15)	DEFAULT NULL	NULL,
	"LIKE_COUNT"	NUMBER	DEFAULT 0	NOT NULL,
	"NO_PAY_COUNT"	NUMBER	DEFAULT 0	NOT NULL
);

COMMENT ON COLUMN "MEMBER"."ATHORITY" IS '1. 회원가입만 한 유저
2. 물품등록 본인인증 한 유저
3. 관리자';

CREATE TABLE "BOARD_IMG" (
	"BOARD_IMG_NO"	NUMBER	DEFAULT SEQ_BOARD_IMG_NO	NOT NULL,
	"BOARD_NO"	NUMBER		NOT NULL,
	"IMG_LEVEL"	VARCHAR2(1)	DEFAULT N	NOT NULL,
	"ORIGIN_NAME"	VARCHAR2(200)		NOT NULL,
	"CHANGE_NAME"	VARCHAR2(500)		NOT NULL
);

CREATE TABLE "COUNTRY" (
	"COUNTRY_NO"	VARCHAR2(3)	DEFAULT KOR	NOT NULL,
	"COUNTRY"	VARCHAR2(30)	DEFAULT 대한민국	NOT NULL
);

CREATE TABLE "BOARD_CATEGORY" (
	"BOARD_CATEGORY_NO"	NUMBER	DEFAULT BOARD_CATEGORY_NO	NOT NULL,
	"BOARD_CATEGORY"	VARCHAR2(30)		NOT NULL
);

COMMENT ON COLUMN "BOARD_CATEGORY"."BOARD_CATEGORY" IS '물품자랑
구매요망';

CREATE TABLE "PAYMENT" (
	"PAYMENT_NO"	NUMBER	DEFAULT SEQ_PAY_NO	NOT NULL,
	"RESULT_NO"	NUMBER		NOT NULL,
	"PAYMENT_METHOD"	VARCHAR2(20)		NULL,
	"PAYMENT_STATUS"	VARCHAR2(1)	DEFAULT N	NULL,
	"PAYMENT_TIME"	DATE	DEFAULT SYSDATE	NOT NULL,
	"PAY_CODE"	VARCHAR2(20)		NULL
);

ALTER TABLE "REPORT_CATEGORY" ADD CONSTRAINT "PK_REPORT_CATEGORY" PRIMARY KEY (
	"REPORT_CATEGORY_NO"
);

ALTER TABLE "NOTI_CD" ADD CONSTRAINT "PK_NOTI_CD" PRIMARY KEY (
	"NOTI_CATEGORY_NO"
);

ALTER TABLE "DELIVERY_DETAIL" ADD CONSTRAINT "PK_DELIVERY_DETAIL" PRIMARY KEY (
	"DELIVERY_DETAIL_NO"
);

ALTER TABLE "BOARD_POST" ADD CONSTRAINT "PK_BOARD_POST" PRIMARY KEY (
	"BOARD_NO"
);

ALTER TABLE "AUTHORITIES" ADD CONSTRAINT "PK_AUTHORITIES" PRIMARY KEY (
	"AUTHORITY"
);

ALTER TABLE "DELIVERY" ADD CONSTRAINT "PK_DELIVERY" PRIMARY KEY (
	"DELIVERY_NO"
);

ALTER TABLE "ITEM_IMG" ADD CONSTRAINT "PK_ITEM_IMG" PRIMARY KEY (
	"ITEM_IMG_NO"
);

ALTER TABLE "USER_SANCTION" ADD CONSTRAINT "PK_USER_SANCTION" PRIMARY KEY (
	"SANCTION_NO"
);

ALTER TABLE "WISHLIST" ADD CONSTRAINT "PK_WISHLIST" PRIMARY KEY (
	"USER_NO",
	"ITEM_NO"
);

ALTER TABLE "RESULT" ADD CONSTRAINT "PK_RESULT" PRIMARY KEY (
	"RESULT_NO"
);

ALTER TABLE "ITEM_CD" ADD CONSTRAINT "PK_ITEM_CD" PRIMARY KEY (
	"ITEM_CATEGORY_NO"
);

ALTER TABLE "BID" ADD CONSTRAINT "PK_BID" PRIMARY KEY (
	"BID_NO"
);

ALTER TABLE "ITEM" ADD CONSTRAINT "PK_ITEM" PRIMARY KEY (
	"ITEM_NO"
);

ALTER TABLE "REPLY" ADD CONSTRAINT "PK_REPLY" PRIMARY KEY (
	"REPLY_NO"
);

ALTER TABLE "NOTIFICATION" ADD CONSTRAINT "PK_NOTIFICATION" PRIMARY KEY (
	"NOTIFICATION_NO"
);

ALTER TABLE "REPORT" ADD CONSTRAINT "PK_REPORT" PRIMARY KEY (
	"REPORT_NO"
);

ALTER TABLE "MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY (
	"USER_NO"
);

ALTER TABLE "BOARD_IMG" ADD CONSTRAINT "PK_BOARD_IMG" PRIMARY KEY (
	"BOARD_IMG_NO"
);

ALTER TABLE "COUNTRY" ADD CONSTRAINT "PK_COUNTRY" PRIMARY KEY (
	"COUNTRY_NO"
);

ALTER TABLE "BOARD_CATEGORY" ADD CONSTRAINT "PK_BOARD_CATEGORY" PRIMARY KEY (
	"BOARD_CATEGORY_NO"
);

ALTER TABLE "PAYMENT" ADD CONSTRAINT "PK_PAYMENT" PRIMARY KEY (
	"PAYMENT_NO"
);

ALTER TABLE "WISHLIST" ADD CONSTRAINT "FK_MEMBER_TO_WISHLIST_1" FOREIGN KEY (
	"USER_NO"
)
REFERENCES "MEMBER" (
	"USER_NO"
);

ALTER TABLE "WISHLIST" ADD CONSTRAINT "FK_ITEM_TO_WISHLIST_1" FOREIGN KEY (
	"ITEM_NO"
)
REFERENCES "ITEM" (
	"ITEM_NO"
);

