-- 1.
SELECT STUDENT_NO 학번, STUDENT_NAME 이름, TO_CHAR(ENTRANCE_DATE,'RRRR-MM-DD') 입학년도
FROM TB_STUDENT
WHERE DEPARTMENT_NO = '002'
--    (SELECT DEPARTMENT_NO 
--    FROM TB_DEPARTMENT 
--    WHERE DEPARTMENT_NAME = '영어영문학과')
ORDER BY ENTRANCE_DATE;

-- 2.
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE PROFESSOR_NAME NOT LIKE '___'
--WHERE LENGTH(PROFESSOR_NAME) <> 3
--WHERE LENGTHB(PROFESSOR_NAME) != 9
;

-- 3.
SELECT PROFESSOR_NAME 교수이름
--, EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM TO_DATE(19 || SUBSTR(PROFESSOR_SSN,1,6))) 나이
, EXTRACT(YEAR FROM SYSDATE) - (19 || SUBSTR(PROFESSOR_SSN,1,2)) 나이
FROM TB_PROFESSOR
WHERE SUBSTR(PROFESSOR_SSN,8,1) = 1
ORDER BY 나이;

-- 4.
SELECT SUBSTR(PROFESSOR_NAME,2) 이름
FROM TB_PROFESSOR;

-- 5.
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE EXTRACT(YEAR FROM ENTRANCE_DATE) - EXTRACT(YEAR FROM TO_DATE(SUBSTR(STUDENT_SSN,1,2), 'RR')) > 19;

-- 6.
SELECT TO_CHAR(TO_DATE('2020-12-25'), 'DAY')
FROM DUAL;

-- 7.
-- TO_DATE('99/10/11','YY/MM/DD') -> 2099년 10월 11일
-- TO_DATE('49/10/11','YY/MM/DD') -> 2049년 10월 11일
-- TO_DATE('99/10/11','RR/MM/DD') -> 1999년 10월 11일
-- TO_DATE('49/10/11','RR/MM/DD') -> 2049년 10월 11일
SELECT TO_CHAR(TO_DATE('99/10/11','YY/MM/DD'), 'YYYY/MM/DD') A,
        TO_CHAR(TO_DATE('49/10/11','YY/MM/DD'), 'YYYY/MM/DD') B,
        TO_CHAR(TO_DATE('99/10/11','RR/MM/DD'), 'RRRR/MM/DD') C,
        TO_CHAR(TO_DATE('49/10/11','RR/MM/DD'), 'RRRR/MM/DD') D
FROM DUAL;

-- 8.
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE SUBSTR(STUDENT_NO, 1,1) <> 'A';
--WHERE STUDENT_NO  NOT LIKE 'A%';

-- 9.
SELECT ROUND(AVG(POINT),1) 평점
FROM TB_GRADE
WHERE STUDENT_NO = 'A517178';

-- 10.
SELECT DEPARTMENT_NO 학과번호, COUNT(*) "학생수(명)"
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO
ORDER BY DEPARTMENT_NO;

-- 11.
SELECT COUNT(*)
FROM TB_STUDENT
WHERE COACH_PROFESSOR_NO IS NULL;

-- 12.
SELECT SUBSTR(TERM_NO,1,4) 년도, ROUND(AVG(POINT),1) "년도 별 평점"
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
GROUP BY SUBSTR(TERM_NO,1,4)
ORDER BY 년도;

-- 13.
SELECT DEPARTMENT_NO 학과코드명, COUNT(DECODE(ABSENCE_YN, 'Y', 1)) "휴학생 수"
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO
ORDER BY 학과코드명;

-- 14.
SELECT STUDENT_NAME 동일이름, COUNT(*) "동명인 수"
FROM TB_STUDENT
GROUP BY STUDENT_NAME
HAVING COUNT(*) >=2
ORDER BY 1;

-- 15.
SELECT SUBSTR(TERM_NO,1,4) 년도, SUBSTR(TERM_NO,5,2) 학기, POINT 평점
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'

UNION ALL

SELECT SUBSTR(TERM_NO,1,4) 년도, NULL 학기, ROUND(AVG(POINT),1) 평점
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
GROUP BY SUBSTR(TERM_NO,1,4)

UNION ALL

SELECT NULL 년도, NULL 학기, ROUND(AVG(POINT), 1) 평점
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
ORDER BY 년도, 학기 NULLS LAST;


SELECT SUBSTR(TERM_NO,1,4) 년도, SUBSTR(TERM_NO,5,2) 학기, ROUND(AVG(POINT), 1) 평점
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
GROUP BY ROLLUP(SUBSTR(TERM_NO,1,4), SUBSTR(TERM_NO,5,2))
ORDER BY 년도, 학기 NULLS LAST;












