-- KH연습문제
-- 1.
SELECT EMP_NAME, EMP_NO, DEPT_TITLE, JOB_NAME
FROM EMPLOYEE E, DEPARTMENT D, JOB J
WHERE (E.DEPT_CODE = D.DEPT_ID)
    AND (E.JOB_CODE = J.JOB_CODE)
    AND SUBSTR(EMP_NO,1,2) BETWEEN 70 AND 79
    AND SUBSTR(EMP_NO,8,1) IN (2,4)
    AND EMP_NAME LIKE '전%';

-- 2.
SELECT EMP_ID, EMP_NAME, 나이, DEPT_TITLE, JOB_NAME
FROM (
    SELECT EMP_ID, EMP_NAME,
        EXTRACT(YEAR FROM SYSDATE) -
        ((CASE SUBSTR(EMP_NO,8,1)
            WHEN '1' THEN 19
            WHEN '2' THEN 19
            WHEN '3' THEN 20
            WHEN '4' THEN 20
            END) || SUBSTR(EMP_NO,1,2))  나이,
        DEPT_TITLE, JOB_NAME
    FROM EMPLOYEE E, DEPARTMENT D, JOB J
    WHERE (E.DEPT_CODE = D.DEPT_ID)
        AND (E.JOB_CODE = J.JOB_CODE)
    ORDER BY 나이
)
WHERE ROWNUM = 1;

-- 3.
SELECT EMP_ID, EMP_NAME, JOB_NAME
FROM EMPLOYEE
JOIN JOB USING(JOB_CODE)
WHERE EMP_NAME LIKE '%전%';

-- 4.
SELECT EMP_NAME, JOB_NAME, DEPT_CODE, DEPT_TITLE
FROM EMPLOYEE E, JOB J, DEPARTMENT D
WHERE (E.JOB_CODE = J.JOB_CODE)
    AND (E.DEPT_CODE = D.DEPT_ID)
    AND (DEPT_CODE IN ('D5','D6'));

-- 5.
SELECT EMP_NAME, BONUS, DEPT_TITLE, LOCAL_NAME
FROM EMPLOYEE E, DEPARTMENT D, LOCATION L
WHERE (E.DEPT_CODE = D.DEPT_ID)
    AND (D.LOCATION_ID = L.LOCAL_CODE)
    AND (BONUS IS NOT NULL);

-- 6.
SELECT EMP_NAME, JOB_NAME, DEPT_TITLE, LOCAL_NAME
FROM EMPLOYEE E, JOB J, DEPARTMENT D, LOCATION L
WHERE (E.JOB_CODE = J.JOB_CODE)
    AND (E.DEPT_CODE = D.DEPT_ID)
    AND (D.LOCATION_ID = L.LOCAL_CODE);

-- 7.
SELECT EMP_NAME, DEPT_TITLE, LOCAL_NAME, NATIONAL_NAME
FROM EMPLOYEE E, DEPARTMENT D, LOCATION L, NATION N
WHERE (E.DEPT_CODE = D.DEPT_ID)
    AND (D.LOCATION_ID = L.LOCAL_CODE)
    AND (L.NATIONAL_CODE = N.NATIONAL_CODE)
    AND (NATIONAL_NAME IN ('한국','일본'));

-- 8.
SELECT E1.EMP_NAME, E1.DEPT_CODE, E2.EMP_NAME
FROM EMPLOYEE E1, EMPLOYEE E2
WHERE E1.DEPT_CODE = E2.DEPT_CODE
    AND E1.EMP_NAME != E2.EMP_NAME
ORDER BY E1.EMP_NAME;

-- 9.
SELECT EMP_NAME, JOB_NAME, SALARY
FROM EMPLOYEE
JOIN JOB USING(JOB_CODE)
WHERE NVL(BONUS,1)=1
    AND JOB_CODE IN ('J4','J7');

-- 10.
SELECT EMP_ID, EMP_NAME, DEPT_TITLE, JOB_NAME, HIRE_DATE, ROWNUM
FROM (SELECT EMP_ID, EMP_NAME, DEPT_TITLE, JOB_NAME, HIRE_DATE
    FROM EMPLOYEE
    LEFT JOIN DEPARTMENT ON DEPT_CODE = DEPT_ID
    JOIN JOB USING(JOB_CODE)
    ORDER BY (SALARY + SALARY * NVL(BONUS,0))*12 DESC)
WHERE ROWNUM <=5;

-- 11.
-- -1
SELECT DEPT_TITLE, SUM(SALARY)
FROM EMPLOYEE
LEFT JOIN DEPARTMENT ON DEPT_CODE = DEPT_ID
GROUP BY DEPT_TITLE
HAVING SUM(SALARY) > (SELECT SUM(SALARY) *0.2 FROM EMPLOYEE);

-- -2
SELECT *
FROM(SELECT DEPT_TITLE, SUM(SALARY) 급여합
    FROM EMPLOYEE
    LEFT JOIN DEPARTMENT ON DEPT_CODE = DEPT_ID
    GROUP BY DEPT_TITLE)
--WHERE "SUM(SALARY)" > (SELECT SUM(SALARY) *0.2 FROM EMPLOYEE)
WHERE 급여합 > (SELECT SUM(SALARY) *0.2 FROM EMPLOYEE)
;

-- -3
WITH EMP_SALARY AS
    (SELECT DEPT_TITLE, SUM(SALARY) 급여합
    FROM EMPLOYEE
    LEFT JOIN DEPARTMENT ON DEPT_CODE = DEPT_ID
    GROUP BY DEPT_TITLE)
SELECT *
FROM EMP_SALARY
WHERE 급여합 > (SELECT SUM(SALARY) *0.2 FROM EMPLOYEE);
    
-- 12.
SELECT DEPT_TITLE, SUM(SALARY)
FROM EMPLOYEE
LEFT JOIN DEPARTMENT ON DEPT_CODE = DEPT_ID
GROUP BY DEPT_TITLE;

-- 13.
WITH EMP_SUMMARY AS
    (SELECT SUM(SALARY), AVG(SALARY)
    FROM EMPLOYEE
    )
SELECT * FROM EMP_SUMMARY;

WITH EMP_SUMMARY AS
    (SELECT SUM(SALARY)
    FROM EMPLOYEE
    UNION
    SELECT AVG(SALARY)
    FROM EMPLOYEE
    )
SELECT * FROM EMP_SUMMARY;















