-- DDL 실습문제
-- 1.
CREATE TABLE TB_CATEGORY(
    NAME VARCHAR2(10),
    USE_YN CHAR(1) DEFAULT 'Y'
);

-- 2.
CREATE TABLE TB_CLASS_TYPE(
    NO VARCHAR2(5) PRIMARY KEY,
    NAME VARCHAR2(10)
);

-- 3.
ALTER TABLE TB_CATEGORY
ADD PRIMARY KEY(NAME);

-- 4.
ALTER TABLE TB_CLASS_TYPE
MODIFY NAME NOT NULL;

-- 5.
ALTER TABLE TB_CATEGORY
MODIFY NAME VARCHAR2(20);

ALTER TABLE TB_CLASS_TYPE
MODIFY NO VARCHAR2(10)
MODIFY NAME VARCHAR2(20);

-- 6.
ALTER TABLE TB_CATEGORY
RENAME COLUMN NAME TO CATEGORY_NAME;

ALTER TABLE TB_CLASS_TYPE
RENAME COLUMN NO TO CLASS_TYPE_NO;
ALTER TABLE TB_CLASS_TYPE
RENAME COLUMN NAME TO CLASS_TYPE_NAME;

-- 7.
ALTER TABLE TB_CATEGORY
RENAME CONSTRAINT SYS_C007175 TO PK_CATEGORY_NAME;

ALTER TABLE TB_CLASS_TYPE
RENAME CONSTRAINT SYS_C007174 TO PK_CLASS_TYPE_NO;

-- 8.
INSERT INTO TB_CATEGORY VALUES('공학','Y');
INSERT INTO TB_CATEGORY VALUES('자연과학','Y');
INSERT INTO TB_CATEGORY VALUES('의학','Y');
INSERT INTO TB_CATEGORY VALUES('예체능','Y');
INSERT INTO TB_CATEGORY VALUES('인문사회','Y');
COMMIT;

-- 9.
ALTER TABLE TB_DEPARTMENT
ADD CONSTRAINT FK_DEPARTMENT_CATEGORY FOREIGN KEY(CATEGORY) REFERENCES TB_CATEGORY;

-- 10.
GRANT CREATE VIEW TO WORKBOOK;
DROP VIEW VW_학생일반정보;

CREATE VIEW VW_학생일반정보
AS SELECT STUDENT_NO 학번, STUDENT_NAME 학생이름, STUDENT_ADDRESS 주소
    FROM TB_STUDENT;

SELECT * FROM VW_학생일반정보;

-- 11.
DROP VIEW VW_지도면담;

CREATE VIEW VW_지도면담
AS SELECT STUDENT_NAME 학생이름, DEPARTMENT_NAME 학과이름, NVL(PROFESSOR_NAME,'지도교수없음') 지도교수이름
    FROM TB_STUDENT
    JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
    LEFT JOIN TB_PROFESSOR ON PROFESSOR_NO = COACH_PROFESSOR_NO
    ORDER BY 2;
    
SELECT * FROM VW_지도면담;

-- 12.
CREATE VIEW VW_학과별학생수
AS SELECT DEPARTMENT_NAME, COUNT(*) STUDENT_COUNT
    FROM TB_STUDENT
    JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
    GROUP BY DEPARTMENT_NAME;

SELECT * FROM VW_학과별학생수;

-- 13.
SELECT * FROM VW_학생일반정보 WHERE 학번 = 'A213046';
SELECT * FROM TB_STUDENT WHERE STUDENT_NO = 'A213046';

UPDATE TB_STUDENT
SET STUDENT_NAME = '서가람'
WHERE STUDENT_NO = 'A213046';

UPDATE VW_학생일반정보
SET 학생이름 = '허승만'
WHERE 학번 = 'A213046';

-- 14.
DROP VIEW VW_학생일반정보;
CREATE OR REPLACE VIEW VW_학생일반정보
AS SELECT STUDENT_NO 학번, STUDENT_NAME 학생이름, STUDENT_ADDRESS 주소
    FROM TB_STUDENT
    WITH READ ONLY;

-- 15.
SELECT CLASS_NO, CLASS_NAME, COUNT(*)
FROM TB_CLASS
JOIN TB_GRADE USING(CLASS_NO)
WHERE 2009 - SUBSTR(TERM_NO,1,4) < 5
GROUP BY CLASS_NO, CLASS_NAME
ORDER BY 3 DESC;

SELECT CLASS_NO, CLASS_NAME, "누적수강생수(명)"
FROM (SELECT CLASS_NO, CLASS_NAME, COUNT(*) "누적수강생수(명)"
    FROM TB_CLASS
    JOIN TB_GRADE USING(CLASS_NO)
    WHERE TERM_NO >= (SUBSTR(ADD_MONTHS(SYSDATE, -60),1,4))
    GROUP BY CLASS_NO, CLASS_NAME
    ORDER BY 3 DESC)
WHERE ROWNUM <=3;

SELECT *
FROM (SELECT CLASS_NO, CLASS_NAME, COUNT(*) "누적수강생수(명)"
    FROM TB_CLASS
    JOIN TB_GRADE USING(CLASS_NO)
    WHERE 2009 - SUBSTR(TERM_NO,1,4) < 5
    GROUP BY CLASS_NO, CLASS_NAME
    ORDER BY 3 DESC)
WHERE ROWNUM <=3;
